# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build emumba-streaming-app`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t emumba-streaming-app`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system emumba-streaming-app && \
          adduser --system -G emumba-streaming-app emumba-streaming-app

COPY dist/emumba-streaming-app emumba-streaming-app/
RUN chown -R emumba-streaming-app:emumba-streaming-app .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix emumba-streaming-app --omit=dev -f install

CMD [ "node", "emumba-streaming-app" ]
